### ISSUE TITLE
Where is it installed?

### ISSUE THREAD

**Issue by ab1nn** [KenKundert/ec#2]
When I type `ec` it shows command not found. I guess the location is not in the path. And also how can I uninstall it?

**Comment by KenKundert** [comment]
You can uninstall `ec` with:
```
pip uninstall engineering_calculator
```
Then, if you re-install it with:
```
pip install --user engineering_calculator
```
the executable will be: `~/.local/bin/ec`.  You will need to add ~/.local/bin` to your path and re-hash it to avoid the command not found error.

**Comment by ab1nn** [comment]
Thanks
